config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'initials#index'
  get 'initials/about'
  get 'events/index'
  get 'events/show'
  get 'mypages/index'
  get 'groups/index'
  get 'groups/show'
  get 'logins/new'

  resources :users
  resources :logins
  resources :groups
  resources :events
  resources :indexs
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get    '/login',   to: 'logins#new' #ログインするためのフォームを表示するページを取得する
  post   '/login',   to: 'logins#create' #新しくメールアドレスやパスワード送信してもらい、データをもとにSessionを作成する
  delete '/logout',  to: 'logins#destroy' #ログアウトでSessionを削除する

   mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  validates :event_name ,presence: true

  belongs_to :group
  
end

app/models/group.rb
class Group < ApplicationRecord

  validates :group_name ,presence: true

  belongs_to :user
  has_many :events
  mount_uploader :image, ImageUploader

end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord
  validates :account_name ,presence: true
  validates :account_name ,uniqueness: true
  validates :account_name ,length: { maximum: 16 }

  validates :mail_address, presence: true
  validates :mail_address, uniqueness: true

  has_secure_password validations: true

  has_many :Groups

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    if params[:group_id] == nil
      flash.now[:danger] = 'イベントが削除されています'
      redirect_to "http://localhost:3000/groups/index"
    else
      @gid = params[:group_id]
      @events = Event.where(group_id: params[:group_id])
      return redirect_to groups_path if @events.nil?
    end
  end

    def show
      @event = Event.find(params[:id])
    end

    def new
      @events = Event.new
     end

    def create
     @event = Event.new(id: params[:event][:id],group_id: session[:group_id],event_name: params[:event][:event_name],event_script: params[:event][:event_script],event_image: params[:event][:event_image],event_day: params[:event][:event_day],event_place: params[:event][:event_place],limit_num_people: params[:event][:limit_num_people],limit_date: params[:event][:limit_date])


     if @event.save
      redirect_to events_path, success: 'イベントの登録が完了しました'
     else
      flash.now[:danger] = "イベントの登録に失敗しました"
     end
   end

     private
     def event_params
      params.require(:event).permit(:id,
                                    :event_name,
                                    :event_script,
                                    :event_image,
                                    :event_day,
                                    :event_place,
                                    :limit_num_people,
                                    :limit_date)
      end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    session[:group_id] = nil
    @groups = Group.all
  end

  def show
    @messages = Message.all
    if params[:id] == nil
      flash.now[:danger] = 'グループが削除されています'
      redirect_to "http://localhost:3000/groups/index"
    else
      session[:group_id] = params[:id]
      @group = Group.find(params[:id])
      @events = Event.where(group_id: params[:id])
      return redirect_to groups_path if @events.nil?
    end
  end


  def new
   @group = Group.new
  end

  def create
   @group = Group.new(group_params)

   if @group.save
    redirect_to groups_path, success: 'グループの登録が完了しました'
   else
    flash.now[:danger] = "グループの登録に失敗しました"
   end
  end

   private
   def group_params
    params.require(:group).permit(:id, :group_name,:group_type, :group_image, :group_comment)
   end

end

app/controllers/initials_controller.rb
class InitialsController < ApplicationController
  def index
    session[:group_id] = nil
  end

  def about
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(account_name: params[:session][:account_name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to 'http://localhost:3000/groups/index', success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  private
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def index
    session[:group_id] = nil
    @name = User.find_by(id: session[:user_id])
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
#    binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to new_login_path, success:'登録が完了しました'
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:account_name, :mail_address, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/initials_helper.rb
module InitialsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<br>
<div class="container">
  <!-- 上部　Welcome Link_Box -->
  <div class="row">
    <div class="col-md-6">
    <h1>EVENT_LIST</h1>
    </div>
      <div class="col-md-3"><%= link_to 'MAKE_GROUP', new_group_path ,class: 'btn-block link_box' %></div>
      <div class="col-md-3"><%= link_to 'MY_PAGE', 'http://localhost:3000/mypages/index' ,class: 'btn-block link_box' %></div>
  </div>

  <p>-------------　↓　イベントアド部分　↓　--------------<p>

  <%= link_to "イベントアド", new_event_path, method: :get %>

  <p>-------------　↑　イベントアド部分　↑　--------------<p>


  <% @events.each do |event| %>
   <div class="row">
     <h2>
      <%= link_to "#{event.event_name}", events_show_path(event, id: "#{event.id}"), method: :get %>
     </h2>
   </div>
  <% end %>

</div>

app/views/events/new.html.erb
<div class="event-top-hero-wrapper text-center">
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <br><br><br><br><br><br>
        <h1 class="text-center text-white">MAKE EVENT!!
        <%= form_for @events do |f| %>
          <div class="form-group">
            <%= f.label :event_name, class: 'text-white' %>
            <%= f.text_field :event_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :event_script, class: 'text-white' %>
            <%= f.text_field :event_script, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :event_image, class: 'text-white' %>
            <%= f.text_field :event_image, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :event_day, class: 'text-white' %>
            <%= f.text_field :event_day, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :event_place, class: 'text-white' %>
            <%= f.text_field :event_place, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :limit_num_people, class: 'text-white' %>
            <%= f.text_field :limit_num_people, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :limit_date, class: 'text-white' %>
            <%= f.text_field :limit_date, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'イベントリストに戻る', events_index_path ,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/events/show.html.erb
<%= @event.event_name %>

app/views/groups/index.html.erb
<br>
<div class="container">
  <!-- 上部　Welcome Link_Box -->
  <div class="row">
    <div class="col-md-6">
      <div class="welcome_name">検索機能部分のほど</div>
    </div>
      <div class="col-md-3"><%= link_to 'MAKE_GROUP', new_group_path ,class: 'btn-block link_box' %></div>
      <div class="col-md-3"><%= link_to 'MY_PAGE', 'http://localhost:3000/mypages/index' ,class: 'btn-block link_box' %></div>
  </div>


  <% @groups.each do |group| %>
   <div class="row">
     <h2>
      <%= link_to "#{group.group_name}", groups_show_path(group, id: "#{group.id}"), method: :get %>
     </h2>
   </div>
  <% end %>

</div>

app/views/groups/new.html.erb
<div class="top-hero-wrapper text-center">
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <br><br><br><br><br><br>
        <h1 class="text-center text-white">MAKE_GROUP</h1>
        <%= form_for @group do |f| %>
          <div class="form-group">
            <%= f.label :group_name, class: 'text-white' %>
            <%= f.text_field :group_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :group_type, class: 'text-white' %>
            <%= f.text_field :group_type, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :group_image, class: 'text-white' %>
            <%= f.text_field :group_image, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :group_comment, class: 'text-white' %>
            <%= f.text_field :group_comment, class: 'form-control' %>
          </div>
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/groups/show.html.erb
<p>-------------　↓　グループ要素部分　↓　-------------<p>
<div class="groupname">
  <%= @group.group_name %>
</div>
<%= @group.group_type %>
<%= @group.group_image %>
<%= @group.group_comment %>

<p>-------------　↑　グループ要素部分　↑　--------------<p>


<p>-------------　↓　チャット部分　↓　--------------<p>

<div id="messages">
  <%= render @messages %>
</div>

<form>
  <label>Say something:</label><br>
  <input type="text" data-behavior="room_speaker">
</form>

<p>-------------　↑　チャット部分　↑　--------------<p>


<p>-------------　↓　イベントリスト部分　↓　--------------<p>

<!-- イベントのカレントの一覧を出す -->
<% @events.each do |event| %>
 <div class="row">
   <h2>
    <%= link_to "　#{event.event_name}", events_show_path(event, id: "#{event.id}"), method: :get %>
   </h2>
 </div>
<% end %>

<p>-------------　↑　イベントリスト部分　↑　--------------<p>

<p>-------------　↓　イベントリストへのリンク部分　↓　--------------<p>

<%= link_to "イベントリスト", events_index_path(group_id: session[:group_id]), method: :get %>

<p>-------------　↑　イベントリストへのリンク部分　↑　--------------<p>

app/views/initials/about.html.erb
<div class="container top-hero-container">
    <div class="col-md-offset-3 col-md-3">
      <%= link_to 'Sign in', new_user_path, class: 'btn btn-block btn-black' %>
    </div>
</div>

app/views/initials/index.html.erb
  <div class="top-hero-wrapper text-center">
    <div class="container top-hero-container">
      <h1 class="text-white">Make Group ! Make Event !</h1>
      <h2 class="text-white">Come On Friend is ...</h2>
      <div class="row">
        <div class="col-md-offset-3 col-md-3">
          <%= link_to 'Sign in', new_user_path, class: 'btn btn-block btn-white' %>
        </div>
        <div class="col-md-3">
          <%= link_to 'Log in', new_login_path,class: 'btn btn-block btn-white' %>
        </div>
        <br><br>
        <div class="col-md-offset-3 col-md-3">
        <h1><span style="text-decoration: underline">
          <%= link_to 'about_Come_On_Friend', initials_about_path %>
        </span></h1>
        </div>
      </div>
    </div>
  </div>

app/views/logins/new.html.erb
<div class="top-hero-wrapper">
  <div class="container top-hero-container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center">Log in</h1>
        <%= form_for :session, url: logins_path do |f| %>
          <div class="form-group">
            <%= f.label :account_name, class: "text-white" %>
            <%= f.text_field :account_name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: "text-white" %>
            <%= f.password_field :password, class: "form-control" %>
          </div>

          <%= f.submit "ログイン", class: "btn-block btn-white" %>
        <% end %>
      </div>
      <%= link_to password_resets_new_path do %>
      <!--実装は後ほど -->
      <div class="pwf">Forget password << CLICK!</div>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/_message.html.erb
<div class="message">
  <p><%= message.content %></p>
</div>

app/views/mypages/index.html.erb
<br>
<div class="container">
  <!-- 上部　Welcome Link_Box -->
  <div class="row">
    <div class="col-md-6">
      <div class="welcome_name">Welcome Back <%= @name.account_name %> !!!</div>
    </div>
      <div class="col-md-3"><%= link_to 'GO_FIND_GROUP', groups_path ,class: 'btn-block link_box' %></div>
      <div class="col-md-3"><%= link_to 'MAKE_GROUP',  new_group_path ,class: 'btn-block link_box' %></div>
  </div>

  <!-- 中部 MyImage MyBgImage Edit 後ほど実装 -->
  <div class="row">
    <div class="col-md-3">MyImage</div>
    <div class="col-md-9">MyBgImage</div>
  </div>

  <!-- 下部 SCHEDULE BELONG -->
  <div class="row">
    <div class="col-md-4">SCHEDULE MAKING EVENT</div>
  　<div class="col-md-8">BELONG GROUP</div>
  </div>
</div>

app/views/password_resets/edit.html.erb
<h1>PasswordResets#edit</h1>
<p>Find me in app/views/password_resets/edit.html.erb</p>

app/views/password_resets/new.html.erb
<h1>PasswordResets#new</h1>
<p>Find me in app/views/password_resets/new.html.erb</p>

app/views/users/new.html.erb
<div class="top-hero-wrapper text-center">
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <br><br><br><br><br><br>
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :account_name, class: 'text-white' %>
            <%= f.text_field :account_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :mail_address, class: 'text-white' %>
            <%= f.text_field :mail_address, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', new_login_path ,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>
</div>